### ISSUE TITLE
MysteriumVPN can't open search engine duckduckgo.com on Windows

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3138]
User reported that after connecting, he can't load any webpages (gets  ERR_TIMED_OUT errors in the browser).
User is in US and connects to US node.

Node: 0.42.1
OS: Windows

Logs:
[mysterium-node 14.log](https://github.com/mysteriumnetwork/node/files/6029954/mysterium-node.14.log)

**Comment by chompomonim** [comment]
Hey, was this issue only with one particular node or it was repeating with many of them?

**Comment by cvl** [comment]
I've asked the user to try other countries, no response from him so far.

In this case I can see from logs there were attempts to connect to two providers:
0x2d3a73085360899a88954f0864a3ae736cf54731
0x79372180aa7c654b1eeebfb80249fa76927e80b7

**Comment by tomasmik** [comment]
Assuming that there such entries in logs like: `API` was started on `2021-02-23T09:26:18.290 INF source/tequilapi/http_api_server.go:77   > API started on: 127.0.0.1:44051` it makes me think that some `myst` process is up or half shut down and is interfering. This might get addressed with desktop app updates.

**Comment by cvl** [comment]
I'm running myst on 44051 to not interfere with MysteriumVPN running on 44050

**Comment by cvl** [comment]
Got more info from the user:

I tried the following and still have the same issues resolving some pages.

My tests below focused on DuckDuckGo.com which has consistently failed when I am connected to Portals:

1. I disabled windows firewall, for all profiles (domain, private, public)
2. I closed Malwarebytes AntiMalware Pro
3. I tested from USA, Canada and Estonia
4. I tried visiting DuckDuckGo.com on Brave Browser and also on Edge Browser
5. I performed NSLookup to DuckDuckGo.com and have included the results below
6. I tried visiting the IP Address returned for duckduckgo.com and it continues to fail loading the page.

USA:
PS C:\Users\userxx> nslookup duckduckgo.com
Server:  UnKnown
Address:  10.182.6.1

Non-authoritative answer:
Name:    duckduckgo.com
Address:  40.89.244.232

Portals OFF: (local)
PS C:\Users\userxx> nslookup duckduckgo.com
Server:  raspberrypi.lan
Address:  192.168.1.86

Non-authoritative answer:
Name:    duckduckgo.com
Address:  52.149.246.39

CANADA:
PS C:\Users\userxx> nslookup duckduckgo.com
Server:  UnKnown
Address:  10.182.5.1

Non-authoritative answer:
Name:    duckduckgo.com
Address:  52.149.246.39

ESTONIA:
PS C:\Users\userxx> nslookup duckduckgo.com
Server:  UnKnown
Address:  10.182.0.1

Non-authoritative answer:
Name:    duckduckgo.com
Address:  40.114.177.156

**Comment by cvl** [comment]
Funny thing, I've tried opening duckduckgo.com by myself - it actually doesn't work.
Loads cnn (slowly), twitter, but duckduckgo is blocked.

Tried nodes:
0xc79be224c5c3bf305dc42c12b19f9f641b41d4aa
0x2d3a73085360899a88954f0864a3ae736cf54731

I'll block those nodes, will see what happens.

I assume this must be some ISP thing of residential nodes - perhaps some ISPs are blocking duckduckgo ?

**Comment by cvl** [comment]
Actually all nodes I've tried are blocking duckduckgo - (even germany nodes).

Must be some dns resolve issue.

**Comment by cvl** [comment]
In general it seems there are many problems related to website loading:
E.g. 0x359cdae6f5ddafc75b4db395b4a9ba0c3f927f29 (Italy) doesn't load cnn.com and duckduckgo.com (loads other websites though).

**Comment by tomasmik** [comment]
Just tested 0x359cdae6f5ddafc75b4db395b4a9ba0c3f927f29

Loaded both duckduckgo.com and cnn.com just fine are you using node or portals? Do these websites work without a vpn connection?

**Comment by cvl** [comment]
Logs from today testing on my PC:
[mysterium-node 21.log](https://github.com/mysteriumnetwork/node/files/6044467/mysterium-node.21.log)

No identity loads duckduckgo.com. cnn.com doesn't load on 0x359cdae6f5ddafc75b4db395b4a9ba0c3f927f29


@tomasmik have you tested on Windows ?

**Comment by cvl** [comment]
Tried now - I can confirm, that this is Windows problem.
Works fine on MacOS.

**Comment by cvl** [comment]
Surely, those websites work perfectly without VPN.

**Comment by cvl** [comment]
Tried MysteriumVPN app 3.5.0 on Windows, same problem.
Logs attached:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6044537/mysterium-node.log)

**Comment by cvl** [comment]
Hi,

Any progress on this so far?

This is kinda critical, as duckduckgo.com is the only search engine with privacy in mind (i.e. anonymous search engine).

**Comment by cvl** [comment]
If this helps, it often fails to open cnn.com as well.

**Comment by cvl** [comment]
bbc.com as well, reddit is very slow
found one identity which opens duckduckgo.com but fails to open most other websites as it's very slow (couldn't load speedtest.net in few minutes): 0xd503c59ae90180150e6f7259d89d3b9d35e79606

**Comment by chompomonim** [comment]
> Funny thing, I've tried opening duckduckgo.com by myself - it actually doesn't work.
> Loads cnn (slowly), twitter, but duckduckgo is blocked.
> 
> Tried nodes:
> 0xc79be224c5c3bf305dc42c12b19f9f641b41d4aa
> 0x2d3a73085360899a88954f0864a3ae736cf54731

I just tried there nodes and duckduckgo.com works fine with them :/

DuckDuckGo is my default search engine, it had some strange issues couple of days ago. At the moment can't reproduce any of those issues :/

**Comment by chompomonim** [comment]
> In general it seems there are many problems related to website loading:
> E.g. 0x359cdae6f5ddafc75b4db395b4a9ba0c3f927f29 (Italy) doesn't load cnn.com and duckduckgo.com (loads other websites though).

One more question. Which DNS do you use in Portals (provider | system | cloudflare) and at which node version you're now there?

**Comment by chompomonim** [comment]
Ok, I can confirm, that with `3.6.0` Mysterium dVPN on Windows there are some strange issues. macOS and Android works fine.

Today we'll test with newest release, will see if issue is still there.

**Comment by cvl** [comment]
Jaro, I believe you're using MacOS. This is occurring just for Windows.
As mentioned, this issue is the same for MysteriumVPN, so it's not Portals problem.

As for dns, I'm using provider DNS, otherwise it'd be the same centralized VPN.

**Comment by cvl** [comment]
Got feedback from Russia, www.megafon.ru doesn't open there as well (together with duckduckgo.com).
That and DNS leaking might be related.

**Comment by cvl** [comment]
my real DNS provider was given out. Thirdly, there were problems with the opening of some sites,
which are not blocked in Russia. I use a Microsoft Edge browser and when I went to www.duckduckgo.com I couldn't open it. Also, the website of the mobile operator Megafon, www.megafon.ru, does not open. These sites are not blocked in Russia. With your VPN through the TOR browser, they open successfully.
If the Portal is disabled, these sites also work successfully.

**Comment by chompomonim** [comment]
We're looking on this issue and investigating potential solutions.

**Comment by cvl** [comment]
thank you @soffokl works well!
