### ISSUE TITLE
NodeUI and mystnodes.com showing incorrect earnings

### ISSUE THREAD

**Issue by cirial** [mysteriumnetwork/node#5683]
New node user here. I've had my node up for about 3 days now.  The NodeUI is showing my earnings at roughly half of what the Mystnodes.com portal  says.  For example at this moment, the NodeUI (localhost) on the computer running the node shows a total 30 day profit (even though I'm 3 days new) as 3.2 myst (the one on Transactions tab and top payment bar on the site).  

The chart in the middle of this site called the "Earnings Report" on the Dashboard tab shows 3.122, which is different than the two places described above.  You cant even say it's rounding up, as if you rounded it would be 3.1 myst. 

Then finally, the balance that is displayed on Mystnodes.com (which I would assume is a way to watch your earnings if you cant directly connect to your node) shows my 30 day earnings as 6.477.  

What gives?  Why are there three completely different values?  I'd assume the value on the "Transactions" tab is what really matters since this is how the system is going to pay out.  Technically it thinks I havent reached the 5 myst payout yet.

**Comment by cirial** [comment]
It just keeps getting more and more off... NodeUI shows I've made about 7 MYST, but Mystnodes.com is leading me to believe I've got a lot more.

![myst_dash](https://user-images.githubusercontent.com/120784313/208291876-1331b32c-4a91-4a59-9380-e3992d5cbbed.png)
![mystnode_site](https://user-images.githubusercontent.com/120784313/208291891-d88308ea-a1e5-4c04-9551-0a52b5786a83.JPG)

**Comment by etherunit** [comment]
Please provide us with your node identity

**Comment by cirial** [comment]
0x919aab592df46ce8033c20e5536c6b32034e0aae

**Comment by cirial** [comment]
Only been paid out 10 MYST (2 myst taken by "the network") so I have 8 MYST in my wallet. 

When do you guys recon i'll see the other 91 MYST that mystnodes.com says i've earned? LOL 
![image](https://user-images.githubusercontent.com/120784313/209051030-5a202c56-ecb8-4457-8220-cecc8df72999.png)

**Comment by Ayse-AK** [comment]
Another one 
https://github.com/mysteriumnetwork/node/issues/5499#issuecomment-1270304533

**Comment by cirial** [comment]
No not resolved :(Sent from my iPhoneOn Dec 26, 2022, at 6:25 AM, Ayse-AK ***@***.***> wrote:﻿
Another one
#5499 (comment)

**Comment by wattCash** [comment]
same here

NodeID is 0x2b85d9fd136ab449c4fabe4a5d236e65479b295c

**Comment by Peter-SovietSquirrel** [comment]
Same issue with 0x826e354626a16b0df3dc9cdaa9a18c186e1197d4

**Comment by etherunit** [comment]
@Ayse-AK Any updates here?

**Comment by tedwardd** [comment]
Same issue here 0xfb986cb599d309845b8de4aef3e11d92f9d41b5a

**Comment by IbrahimDevX** [comment]
Same issue here
https://github.com/mysteriumnetwork/node/issues/5692

**Comment by IbrahimDevX** [comment]
It just got worse. Now it reset on mystnodes.com to 0 MYST from 400 MYST AND WON'T PROGRESS... :(

**Comment by cirial** [comment]
Mine seems to be reflecting what I see on NodeUI. Don’t worry about what it said on mystnodes - those were way wrong. You didn’t have 400 Myst  Sent from my iPhoneOn Jan 7, 2023, at 9:59 AM, Ibrahim imran ***@***.***> wrote:﻿
It just got worse. Now it reset on mystnodes.com to 0 MYST from 400 MYST AND WON'T PROGRESS... :(

**Comment by IbrahimDevX** [comment]
On my NodeUI it shows 2 Myst

**Comment by wattCash** [comment]
Well, disconnecting mystnodes is clearly not the way to go, as it seems you are hiding your dirty laundry, by denying users the opportunity to double check their earnings. You want users to believe the reported earnings on the local node, but as you can see from the attached picture, the accounting on the transferred data is obviously wrong because over 7 days the local Node is reporting 38GiB transferred, yet  session (33032458) that transferred 59..33 GB within the last 2 days. This translates into an inaccurate earnings calculation local node. 
![Wrong_accounting](https://user-images.githubusercontent.com/55939391/212520050-3914dd28-29eb-440f-8b8f-ee887401f285.png)

**Comment by cirial** [comment]
I think I saw mine was fixed for a little while - now Mystnodes.com is back
to showing I've made triple what I've been paid out.  REALLY frustrating

**Comment by cirial** [comment]
> Well, disconnecting mystnodes is clearly not the way to go, as it seems you are hiding your dirty laundry, by denying users the opportunity to double check their earnings. You want users to believe the reported earnings on the local node, but as you can see from the attached picture, the accounting on the transferred data is obviously wrong because over 7 days the local Node is reporting 38GiB transferred, yet session (8de59ca7) that transferred 59.33 GB within the last 2 days. This in turn translates into an inaccurate earnings calculation on local node. ![Wrong_accounting](https://user-images.githubusercontent.com/55939391/212520050-3914dd28-29eb-440f-8b8f-ee887401f285.png)

I think in your case - you'll get the MYST for that 59gb session once they disconnect.

**Comment by wattCash** [comment]
Nope. As you can see from the screenshot:  the session has ended ( I believe it was not active on the 16th when I checked), and the history of the last 30 days does not give me credit for that. 

![Screenshot from 2023-01-19 20-57-07](https://user-images.githubusercontent.com/55939391/213601693-d0f49ee0-aefc-4deb-9faa-17d6991209b3.png)

**Comment by etherunit** [comment]
@cirial @wattCash I'm following up on this one. Team did some important improvements in reflecting data. Can you please check on your end and confirm it works better now?

**Comment by IbrahimDevX** [comment]
Wondering if anybody is still having problems. I've put off deploying many nodes because of this, and have since taken down all of my nodes from Mysterium.

**Comment by etherunit** [comment]
@IbrahimDevX As mentioned, we did quite a few improvements there. Please let us know if you are still facing any discrepancies in metrics such as earnings, data transfer, session counts etc.
